/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myshopmana;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Admin
 */
public class CategoryForm extends javax.swing.JFrame {

    /**
     * Creates new form CategoryForm
     */
    public CategoryForm() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
        show_table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        backButton = new javax.swing.JLabel();
        searchPr = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        CategoryTx = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        prodButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        productTable.setAutoCreateRowSorter(true);
        productTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        productTable.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Product Name", "Category", "Unit", "Quantity", "Price"
            }
        ));
        productTable.setToolTipText("");
        productTable.setColumnSelectionAllowed(true);
        productTable.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(productTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 770, 290));

        backButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        backButton.setForeground(new java.awt.Color(204, 204, 255));
        backButton.setText("<Back");
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });
        jPanel1.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        searchPr.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        searchPr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchPrActionPerformed(evt);
            }
        });
        searchPr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchPrKeyReleased(evt);
            }
        });
        jPanel1.add(searchPr, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 170, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setText("Filter:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, -1, 30));

        CategoryTx.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CategoryTx.setForeground(new java.awt.Color(24, 24, 24));
        CategoryTx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Fruits", "Fish & Shellfish", "Bread & Bakery", "Personal Care", "Vegetables", "Canned goods", "Frozen Foods", "Meat", "Sauce & Oils", "Snacks", "Beverages", "Rice", "Household", "Others" }));
        CategoryTx.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CategoryTxItemStateChanged(evt);
            }
        });
        jPanel1.add(CategoryTx, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 180, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 255));
        jLabel2.setText("Search:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, 30));

        prodButton.setBackground(new java.awt.Color(204, 204, 255));
        prodButton.setText("Product");
        prodButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        prodButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prodButtonMouseClicked(evt);
            }
        });
        jPanel1.add(prodButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, 90, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        // TODO add your handling code here:
        ManagerForm mf = new ManagerForm();
        mf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backButtonMouseClicked

    private void searchPrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchPrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchPrActionPerformed

    private void searchPrKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchPrKeyReleased
        // TODO add your handling code here:
        String search = searchPr.getText();
        DefaultTableModel model = (DefaultTableModel)productTable.getModel();
        TableRowSorter trs = new TableRowSorter(model);
        productTable.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_searchPrKeyReleased

    private void CategoryTxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CategoryTxItemStateChanged
        // TODO add your handling code here:
        String query = CategoryTx.getSelectedItem().toString();
        filter(query);
    }//GEN-LAST:event_CategoryTxItemStateChanged

    private void prodButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prodButtonMouseClicked
        // TODO add your handling code here:
        ProductForm pf = new ProductForm();
        pf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_prodButtonMouseClicked
    public void show_table(){
        ProductForm pf = new ProductForm();
        ArrayList<Product> products = pf.datalist();
        DefaultTableModel model = (DefaultTableModel)productTable.getModel();
        Object[] rows = new Object[6];
        for(int i=0;i<products.size();i++){
            rows[0] = products.get(i).getProductID();
            rows[1] = products.get(i).getProductName();
            rows[2] = products.get(i).getProductCategory();
            rows[3] = products.get(i).getProductUnit();
            rows[5] = products.get(i).getPrice();
            rows[4] = products.get(i).getQuantity();
            model.addRow(rows);
        }
    }
    private void filter(String query){
         DefaultTableModel model = (DefaultTableModel)productTable.getModel();
        TableRowSorter trs = new TableRowSorter(model);
        productTable.setRowSorter(trs);
        if(query != "None"){
            trs.setRowFilter(RowFilter.regexFilter(query));
        } else {
            productTable.setRowSorter(trs);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CategoryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CategoryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CategoryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CategoryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CategoryForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CategoryTx;
    private javax.swing.JLabel backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton prodButton;
    private static javax.swing.JTable productTable;
    private javax.swing.JTextField searchPr;
    // End of variables declaration//GEN-END:variables
}
