/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myshopmana;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.print.PrinterException;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Admin
 */
public class SalaryFormy extends javax.swing.JFrame {

    /**
     * Creates new form SalaryFormy
     */
    private String id;
    public SalaryFormy() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
        show_table();
       
    }
    // cong luong
    public void setId(String id){
        this.id = id;
    }
    public String getId(){
        return id;
    }
    public ArrayList<Salary> datalist(){
        ArrayList<Salary> data = new ArrayList<>();
        try{
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost/salesmanager","root","");
            String query = "SELECT * FROM salary";
            java.sql.Statement st = connection.createStatement();
            ResultSet rs = st.executeQuery(query);
            Salary salary;
            while(rs.next()){
                salary = new Salary(rs.getString("ID"),rs.getString("fullName"), rs.getDouble("basicSalary"), rs.getInt("totalSales")
                        ,rs.getDouble("additions"));
                //System.out.println(rs.getDouble("basicSalary"));
                data.add(salary);
            }
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        return data;
    }
     
    public void show_table(){
        ArrayList<Salary> salarys = datalist();
        DefaultTableModel model = (DefaultTableModel)salaryTable.getModel();
        Object[] rows = new Object[6];
       // System.out.println(salarys.get(0).getBasicSalary());
        for(int i=0;i<salarys.size();i++){
            rows[0] = salarys.get(i).getID();
            rows[1] = salarys.get(i).getName();
            rows[2] = salarys.get(i).getBasicSalary();
            rows[3] = salarys.get(i).getToTalSales();
            rows[4] = salarys.get(i).getAdditions();
            rows[5] = salarys.get(i).getTotalSalary();
            model.addRow(rows);
        }
    }
    public void writeUser(String id) throws FileNotFoundException{
        try{
            PrintWriter pw = new PrintWriter(new File("F:\\PROGRAMMING\\myShopMana\\src\\resource\\ID.txt"));
            pw.print(id);
            pw.close();
        } catch(Exception e){
            System.out.println("Can't load file");
        }
    }
    public void reloadFile(){
         try{
            PrintWriter pw = new PrintWriter(new File("F:\\PROGRAMMING\\myShopMana\\src\\resource\\ID.txt"));
            pw.print("");
            pw.close();
        } catch(Exception e){
            System.out.println("Can't load file");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backButton = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        salaryTable = new javax.swing.JTable();
        PrintBtt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        editbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(224, 224, 242));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        backButton.setText("<Back");
        backButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });
        jPanel1.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        salaryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "FULLNAME", "BASIC SALARY", "TOTAL SALES", "ADDITIONS", "TOTAL SALARY"
            }
        ));
        salaryTable.setGridColor(new java.awt.Color(51, 51, 51));
        salaryTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salaryTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(salaryTable);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 760, 300));

        PrintBtt.setBackground(new java.awt.Color(0, 0, 204));
        PrintBtt.setText("PRINT");
        PrintBtt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PrintBttMouseClicked(evt);
            }
        });
        PrintBtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintBttActionPerformed(evt);
            }
        });
        jPanel1.add(PrintBtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Salary Report");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        editbutton.setBackground(new java.awt.Color(0, 0, 204));
        editbutton.setText("EDIT");
        editbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editbuttonMouseClicked(evt);
            }
        });
        editbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(editbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 400, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        // TODO add your handling code here:
        ManagerForm managerForm = new ManagerForm();
        managerForm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backButtonMouseClicked
    
    private void salaryTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salaryTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)salaryTable.getModel();
        int row = salaryTable.getSelectedRow();
        try {
            writeUser(model.getValueAt(row, 0).toString());
        } catch (FileNotFoundException ex) {
            Logger.getLogger(SalaryFormy.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_salaryTableMouseClicked

    private void PrintBttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintBttActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrintBttActionPerformed

    private void PrintBttMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PrintBttMouseClicked
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            salaryTable.print();
            
        } catch (PrinterException ex) {
            Logger.getLogger(BillForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PrintBttMouseClicked

    private void editbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editbuttonMouseClicked
        // TODO add your handling code here:
        EditSalary es = new EditSalary();
        es.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_editbuttonMouseClicked

    private void editbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalaryFormy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalaryFormy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalaryFormy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalaryFormy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalaryFormy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PrintBtt;
    private javax.swing.JLabel backButton;
    private javax.swing.JButton editbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private static javax.swing.JTable salaryTable;
    // End of variables declaration//GEN-END:variables
}
